### ISSUE TITLE
Image

### ISSUE THREAD

**Issue by Islombek-FD** [MatthewHerbst/react-to-print#639] opened 2023-09-06 05:03 UTC
Hello everyone, I want to print a react-component using the react-to-print box, but the image is blurry. How can I run this? Thanks beforehand.
![image](https://github.com/gregnb/react-to-print/assets/89459802/a72b176d-e6c2-40a0-9dd6-438d89d59369)

**Comment by MatthewHerbst** [comment] 2023-09-06 05:12
Hello. Can you please confirm that the image is not blurry if you print just using regular ctrl+p/cmd+p?

Also, if you could make a working [Codesandbox](https://codesandbox.io/s/rzdhd) the replicates the problem it would be appreciated, thanks!

**Comment by Islombek-FD** [comment] 2023-09-06 05:23
```typescript
import React, { useEffect, useRef } from 'react';
import { useTranslation } from 'react-i18next';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { useReactToPrint } from 'react-to-print';
import cx from 'classnames';

import { LANGUAGE } from '@/helpers/enums';

import { useGenerate } from '@/modules/ticket/hooks';

import Logo from '@/assets/images/logo.svg';
import TicketBox from '@/assets/images/ticket_box.png';

import Icon from '@/components/Icon';
import Header from '@/components/Header';
import Spinner from '@/components/Spinner';

import cls from './Ticket.module.scss';

const Ticket: React.FC = () => {
  const { t, i18n } = useTranslation();
  const navigate = useNavigate();
  const [query] = useSearchParams();
  const ticketRef = useRef();

  const queueId = query.get('queueId');
  const parentServiceId = query.get('parentServiceId');
  const childServiceId = query.get('childServiceId');

  const { mutate, data, isLoading } = useGenerate();

  useEffect(() => {
    const backToHome = setTimeout(() => {
      navigate('/');
    }, 15000);

    return () => {
      clearTimeout(backToHome);
    };
  }, []);

  const handlePrint = useReactToPrint({
    content: () => ticketRef.current,
    pageStyle: `
      @media print {
         body { 
           -webkit-print-color-adjust: exact; 
           padding: 60px 0 20px !important;
         } 
      }
    `,
  });

  useEffect(() => {
    if (!!queueId && !!parentServiceId) {
      mutate(
        { params: { queueId, parentServiceId, childServiceId, locale: i18n.language as LANGUAGE } },
        {
          onSuccess: () => {
            setTimeout(() => {
              handlePrint();
            }, 1000);
          },
        },
      );
    }
  }, [queueId, parentServiceId, childServiceId]);

  return (
    <div className={cls.wrapper}>
      <Header />

      {isLoading ? (
        <div className={cls.spinner}>
          <Spinner spinning />
        </div>
      ) : data ? (
        <div className={cls.content}>
          <div className={cls.machine}>
            <img src={TicketBox} alt='Ticket box' />

            <div className={cls.ticket} ref={ticketRef}>
              <div className={cls.ticketHeader}>
                <img src={Logo} alt='Logo' width={45} />
                <div className={cls.ticketMinistry}>Adliya vazirligi</div>
              </div>

              <div className={cls.ticketContent}>
                <div className={cls.ticketWelcome}>Xush kelibsiz!</div>
                <div className={cls.ticketQueue}>Sizning navbatingiz:</div>
                <div className={cls.ticketQueueNumber}>
                  {`${data.ticketPrefix}${data.ticketNumber}`}
                </div>
                <div className={cls.ticketOrder}>
                  Sizdan oldingi navbat {data.order}
                </div>
              </div>

              <div className={cls.ticketFooter}>
                <div className={cls.ticketDate}>{data.date}</div>
                <div className={cls.ticketTime}>{data.time}</div>
              </div>
            </div>
          </div>

          <div className={cx(cls.circle, cls.large)}>
            <div className={cx(cls.circle, cls.small)}>
              <Icon name='ChevronDown' size={24} />
            </div>
          </div>
        </div>
      ) : (
        <div>{t('ticket_not_created')}</div>
      )}
    </div>
  );
};

export default Ticket;
``` 
In this case, when the ticket is created, I'm printing automatically without using ctrl+p

**Comment by Islombek-FD** [comment] 2023-09-06 05:24
![image](https://github.com/gregnb/react-to-print/assets/89459802/6b8bc7e1-8cd9-4e93-a398-466f1d137bc6)
I want to print this component

**Comment by Islombek-FD** [comment] 2023-09-06 05:26
Is it possible to print in image view of react component?

**Comment by MatthewHerbst** [comment] 2023-09-06 05:37
Your code looks ok.

> In this case, when the ticket is created, I'm printing automatically without using ctrl+p

Sure, but as a test, try printing with `ctrl+p`. It will let us determine if the issue is with `react-to-print` or with your images and/or styles

**Comment by Islombek-FD** [comment] 2023-09-06 05:42
![image](https://github.com/gregnb/react-to-print/assets/89459802/b0b3fbb8-8eb5-4e92-9095-10821909227d)
ctrl+p

**Comment by MatthewHerbst** [comment] 2023-09-06 06:07
Thanks! So the image (face) is blurry there too, which likely means the issue is not with `react-to-print`. Can you link to an example image you are trying to print? Maybe it's not high-quality enough, or maybe it's so big that the browser can't download it quick enough before the print needs to happen?

**Comment by MatthewHerbst** [comment] 2023-09-22 07:33
Going to close this for now. Please let me know if it's still a issue and we can re-open

**Closed as completed by MatthewHerbst** 2023-09-22 07:33 UTC
