### ISSUE TITLE
Styles are not properly rendered in iframe because of missing DOCTYPE

### ISSUE THREAD

**Issue by mukul-rawat** [MatthewHerbst/react-to-print#459] opened 2022-01-19 14:26 UTC
### This is the alignment that is being rendered on the UI.
![150278059-bf5c539a-2131-41ba-907a-4d6d87834c25](https://github.com/gregnb/react-to-print/assets/90625400/adf12512-8b56-4f8b-92e5-4d60fa2151cb)

### This is the alignment that is being rendered in the print
![150278059-bf5c539a-2131-41ba-907a-4d6d87834c25 (2)](https://github.com/gregnb/react-to-print/assets/90625400/0bc03181-4c81-4f9f-9a00-45c0ceafbb00)

Probable cause is that the iframe is missing the `<!DOCTYPE html>` 

Browser: Latest version of Chrome

**Comment by MatthewHerbst** [comment] 2022-01-19 17:59
Hello. Could you please share code to reproduce the print output? A working codesandbox would be ideal. I'm not aware of a missing DOCTYPE being able to impact styles, and if it did then this package would be breaking for everyone that uses it. I'm guessing there is a CSS issue in your code.

**Comment by mukul-rawat** [comment] 2022-01-20 07:36
@MatthewHerbst This is the sandbox that uses the minimal code to replicate the issue https://codesandbox.io/s/cranky-platform-fi9rr

The same results can be reproduced in raw HTML https://codesandbox.io/s/sleepy-currying-ju634

**Comment by MatthewHerbst** [comment] 2022-01-24 22:53
The fix for this will be in the next patch release, which will be released this week, possibly even today.

Lots of learning from looking into this, thanks for the report.

Some references for anyone else reading this:
https://developer.mozilla.org/en-US/docs/Glossary/Doctype
https://developer.mozilla.org/en-US/docs/Web/HTML/Quirks_Mode_and_Standards_Mode
https://hsivonen.fi/doctype/
https://quirks.spec.whatwg.org/#css

There must be something unique in the styles that is causing the browser to do strange things in quirks mode, since otherwise I would have expected this to have been reported a long time ago. I wasn't able to see anything obvious with a semi-thorough read through the code so it must be some pretty arcane rule in the CSS quirks mode being triggered. Regardless, you are correct that we should be setting the `DOCTYPE` so that we always are rendered in standards mode.

**Comment by MatthewHerbst** [comment] 2022-01-24 23:31
Fix published in `v2.14.4`, thanks!

**Closed as completed by MatthewHerbst** 2022-01-24 23:31 UTC
Labels: bug, CSS

**Comment by mukul-rawat** [comment] 2022-01-25 05:11
@MatthewHerbst Thanks for the quick replies and the fix.
