### ISSUE TITLE
onBeforeGetContent is not printing when a content changes

### ISSUE THREAD

**Issue by Biaggio74** [MatthewHerbst/react-to-print#169] opened 2019-09-25 11:07 UTC
The **onBeforeGetContent** is working properly when following the example files and it changes the content of the text from _'00000000'_ to _"text changed"_.
However, the changes is not reflected neither in the printing UI nor in the printed page itself.

**Comment by MatthewHerbst** [comment] 2019-10-16 19:45
Hello, sorry for the very delayed response. When I run the example locally the text changes in the browser window and is properly changed in the print window. Can you please explain how you were able to see it not work properly?

**Comment by christianandrei** [comment] 2019-10-23 08:01
Hi! 

I have a **PrescriptionPad** component and the content of that depends on a state. When I changed the state inside **onBeforeGetContent** the UI changed but not reflected in print preview. I believed the setState is asynchronuos that's why its not reflected on the print preview. How to achieve that? Thanks!

```jsx
<ReactToPrint
  trigger={() => (
    <Button size="small" type="primary">
      <Icon type="printer" /> Print Prescription
    </Button>
  )}
  content={() => prescriptionPadRef.current}
  onBeforeGetContent={() =>
    //perform setState here
  }
/>
```

**Comment by MatthewHerbst** [comment] 2019-10-23 08:24
Hi @christianandrei you need to return a Promise that resolve when the `setState` call completes. `setState` has a callback that is called after changes have been committed, so you just need to resolve the promise there:

```jsx
handleBeforeGetContent = () => {
  return new Promise((resolve, reject) => {
    this.setState({ key: 'updatedValue' }, () => resolve());
  });
}
```

**Comment by christianandrei** [comment] 2019-10-23 09:30
> Hi @christianandrei you need to return a Promise that resolve when the `setState` call completes. `setState` has a callback that is called after changes have been committed, so you just need to resolve the promise there:
> 
> ```js-jsx
> handleBeforeGetContent = () => {
>   return new Promise((resolve, reject) => {
>     this.setState({ key: 'updatedValue' }, () => resolve());
>   });
> }
> ```

I'm using react hooks and setState (useState) there has no callback function. May I know how to do it in react hooks version? Thank you very much!

**Comment by sergeyshmakov** [comment] 2019-10-24 20:25
@christianandrei Just try to return `Promise.resolve()` in function where you do `setState`.

```javascript
handleBeforeGetContent = () => {
  setState({ key: 'updatedValue' });
  return Promise.resolve();
}
```

**Comment by MatthewHerbst** [comment] 2019-10-24 23:35
@sergeyshmakov that won't work because `setState` is asynchronous, meaning you *must* wait for it to finish before resolving the promise.

@christianandrei I haven't tested it, but I think you want something like this:

```jsx
const MyFunctionalComponent = (props) => {
  const [counterOptions, setCounterOptions] = useState({ counter: 0, resolve: undefined });
  
  useEffect(() => {
    counterOptions.resolve();
  }, [counterOptions]);

  return (
    <ReactToPrint
      onBeforeGetContent={() =>
        return new Promise((resolve) => {
          setCounterOptions(prevOptions => ({ counter: prevOptions.counter + 1, resolve }));
        });
      }
    />
  );
}
```

**Comment by sergeyshmakov** [comment] 2019-10-25 07:14
@MatthewHerbst Actually it will works. Because of `Promise.resolve()` create asynchronous call.

**Comment by MatthewHerbst** [comment] 2019-10-25 07:46
@sergeyshmakov It will not work. `Promise.resolve` does create a Promise, but it will not wait to resolve that promise until the state update is complete, which is what we are trying to do here.

**Comment by sergeyshmakov** [comment] 2019-10-25 10:28
@MatthewHerbst How I understand - you guys need to get actual HTML after `setState`. Just watch this short example with `console.log`.

https://jsfiddle.net/sergeyshmakov/jhdpvtu5/

**Comment by MatthewHerbst** [comment] 2019-10-25 19:06
@sergeyshmakov that merely _appears_ to work because the state update is happening quickly. There is no guarantee that state updates will always happen quickly.

**Comment by sergeyshmakov** [comment] 2019-10-25 19:33
@MatthewHerbst Partly you're right but this solution is ok if you dont do async actions in `setState`. And this is not depends on DOM-size of react component.

Your solution is more "honest" yes, but we need to check that `resolve` exist and also remove it from state after `resolve()` call.

```jsx
const MyFunctionalComponent = (props) => {
  const [counterOptions, setCounterOptions] = useState({ counter: 0, resolve: undefined });
  
  useEffect(() => {
    const {resolve, ...otherState} = counterOptions;
    if (resolve) {
        resolve();
        setCounterOptions({ ...otherState, resolve: undefined });
    }
  }, [counterOptions]);

  return (
    <ReactToPrint
      onBeforeGetContent={() =>
        return new Promise((resolve) => {
          setCounterOptions(prevOptions => ({ counter: prevOptions.counter + 1, resolve }));
        });
      }
    />
  );
}
```

**Comment by MatthewHerbst** [comment] 2019-10-25 22:27
@sergeyshmakov I think you misunderstand a bit. [`setState` itself is asynchronous](https://reactjs.org/docs/state-and-lifecycle.html#state-updates-may-be-asynchronous), regardless of what state you actually change.

Also, there is no need to clear out the `resolve` since the `useEffect` hook will _only_ run when the `counter` changes, and the `counter` can only change in the one spot where we specify changing it, where we also set the new `resolve`. In fact, resetting the `resolve` as you do in your example causes a needless re-render of the component.

**Comment by christianandrei** [comment] 2019-10-28 01:23
> @sergeyshmakov that won't work because `setState` is asynchronous, meaning you _must_ wait for it to finish before resolving the promise.
> 
> @christianandrei I haven't tested it, but I think you want something like this:
> 
> ```js-jsx
> const MyFunctionalComponent = (props) => {
>   const [counterOptions, setCounterOptions] = useState({ counter: 0, resolve: undefined });
>   
>   useEffect(() => {
>     counterOptions.resolve();
>   }, [counterOptions]);
> 
>   return (
>     <ReactToPrint
>       onBeforeGetContent={() =>
>         return new Promise((resolve) => {
>           setCounterOptions(prevOptions => ({ counter: prevOptions.counter + 1, resolve }));
>         });
>       }
>     />
>   );
> }
> ```

@MatthewHerbst Yes! That is what I want but I've not tested your code because many changes will happen in my code if I change my state structure (my state is array and not object). I solved it by hidding the ReactToPrint component and attaching a ref to it and trigger the print inside useEffect

```jsx
let prescriptionPadRTPRef = React.createRef();

useEffect(() => {
     if (prescriptionPadRTPRef.current) {
          prescriptionPadRTPRef.current.handlePrint();
     }
}, [prescriptions]);

const handlePrescriptionPadPrint = () => {
   //perform prescriptions state change here
};

<Button
    size="small"
    type="primary"
    onClick={handlePrescriptionPadPrint}
>
    <Icon type="printer" /> Print
    Prescription
</Button>
<div style={{ display: "none" }}>
    <ReactToPrint
        ref={r => {
            prescriptionPadRTPRef.current = r;
        }}
        trigger={() => <button>print</button>}
        content={() =>
            prescriptionPadRef.current
        }                                            
    />
</div>
```

It would be nice if the print can trigger using state change like: 

```jsx
<ReactToPrint
    print={true|false}
/>
```

Hopefully to implent it in future.
Thank you very much!

**Closed as completed** 2019-10-28 01:30 UTC
Labels: bug, unverified

**Comment by justinwang189** [comment] 2020-01-21 05:08
@MatthewHerbst tested and confirmed your snippet worked great!
(one small fix is to make initialization of resolve a function)
```
  const [counterOptions, setCounterOptions] = useState({ counter: 0, resolve: () => undefined });
```

**Comment by alejandroyunes** [comment] 2020-10-03 20:02
hello everyone,
can anybody help me, I am having issues with react to print.  The problem is that when the UI changes and the state updates, when I hit the print ref button it still brings the old pdf with the privious data, no matter how many times I save and the state updates.  the only work around to see the new print preview is if I reload the browser.

`content={() => this.refPrintableArea.current}
trigger={() => <button style={{display: 'none'}} ref={this.refPrintButton}>Print</button>}`

**Comment by MatthewHerbst** [comment] 2020-10-03 23:50
@alejandroyunes could you share a codesandbox showing your code please?

**Comment by chirag773** [comment] 2020-10-06 10:29
I want some component that should be hidden in the start and when I click on the print button it should show and can be printable how do it?

**Comment by MatthewHerbst** [comment] 2020-10-06 18:59
@chirag773 see the examples in this code base, such as: https://github.com/gregnb/react-to-print/blob/28365f179aa181dd489c2d99484673eb99cf7684/example/ClassComponent/index.tsx#L26

**Comment by umerfarooqQC** [comment] 2021-07-14 12:09
I had also a same problem in Microsoft edge it was prininting before state change inside onbeforegetcontent. 
Promise resolve fixed inside onbeforegetcontent fixed my issue.

**Comment by tkMageztik** [comment] 2022-01-14 04:51
In my case, was not necesary make resolve a function... , so this works awesome:

`const [counterOptions, setCounterOptions] = useState({ counter: 0, resolve: undefined });`

**Comment by zakarehman270** [comment] 2022-06-14 04:31
I have a problem React-to-print half text remain upper page and half remain lower page when print large content ??? please help
[ZULQARNAIN ALI ABID444.pdf](https://github.com/gregnb/react-to-print/files/8896394/ZULQARNAIN.ALI.ABID444.pdf)

**Comment by MatthewHerbst** [comment] 2022-06-14 05:26
@zakarehman270 please make a new issue for your problem, and include your code, thank you

**Comment by zakarehman270** [comment] 2022-06-14 05:48
@[MatthewHerbst](https://github.com/MatthewHerbst)
![image](https://user-images.githubusercontent.com/104195807/173502243-fc3c28dd-7596-4171-9a95-810b104900f8.png)


> @zakarehman270 please make a new issue for your problem, and include your code, thank you
This is my code  
<ReactToPrint
              pageStyle="@page { size: auto; margin: 18mm; } }"
              content={reactToPrintContent}
              documentTitle={ResumeName}
              onAfterPrint={handleAfterPrint}
              onBeforeGetContent={handleOnBeforeGetContent}
              onBeforePrint={handleBeforePrint}
              removeAfterPrint
              trigger={reactToPrintTrigger}
            />
My issue is that when I print some large text then some text remain upper page and some text remain lower page

**Comment by zakarehman270** [comment] 2022-06-14 05:49
> @zakarehman270 please make a new issue for your problem, and include your code, thank you
<ReactToPrint
              pageStyle="@page { size: auto; margin: 18mm; } }"
              content={reactToPrintContent}
              documentTitle={ResumeName}
              onAfterPrint={handleAfterPrint}
              onBeforeGetContent={handleOnBeforeGetContent}
              onBeforePrint={handleBeforePrint}
              removeAfterPrint
              trigger={reactToPrintTrigger}
            />

**Comment by zakarehman270** [comment] 2022-06-14 05:51
` <ReactToPrint
              pageStyle="@page { size: auto; margin: 18mm; } }"
              content={reactToPrintContent}
              documentTitle={ResumeName}
              onAfterPrint={handleAfterPrint}
              onBeforeGetContent={handleOnBeforeGetContent}
              onBeforePrint={handleBeforePrint}
              removeAfterPrint
              trigger={reactToPrintTrigger}
            />`

**Comment by zakarehman270** [comment] 2022-06-14 06:23
I have a problem on React-Print . It is not print background color????

**Comment by MatthewHerbst** [comment] 2022-06-14 09:17
@zakarehman270 https://github.com/gregnb/react-to-print/issues/500

**Comment by MrKham** [comment] 2023-07-14 04:47
> > @sergeyshmakov that won't work because `setState` is asynchronous, meaning you _must_ wait for it to finish before resolving the promise.
> > @christianandrei I haven't tested it, but I think you want something like this:
> > ```
> > const MyFunctionalComponent = (props) => {
> >   const [counterOptions, setCounterOptions] = useState({ counter: 0, resolve: undefined });
> >   
> >   useEffect(() => {
> >     counterOptions.resolve();
> >   }, [counterOptions]);
> > 
> >   return (
> >     <ReactToPrint
> >       onBeforeGetContent={() =>
> >         return new Promise((resolve) => {
> >           setCounterOptions(prevOptions => ({ counter: prevOptions.counter + 1, resolve }));
> >         });
> >       }
> >     />
> >   );
> > }
> > ```
> 
> @MatthewHerbst Yes! That is what I want but I've not tested your code because many changes will happen in my code if I change my state structure (my state is array and not object). I solved it by hidding the ReactToPrint component and attaching a ref to it and trigger the print inside useEffect
> 
> ```js
> let prescriptionPadRTPRef = React.createRef();
> 
> useEffect(() => {
>      if (prescriptionPadRTPRef.current) {
>           prescriptionPadRTPRef.current.handlePrint();
>      }
> }, [prescriptions]);
> 
> const handlePrescriptionPadPrint = () => {
>    //perform prescriptions state change here
> };
> 
> <Button
>     size="small"
>     type="primary"
>     onClick={handlePrescriptionPadPrint}
> >
>     <Icon type="printer" /> Print
>     Prescription
> </Button>
> <div style={{ display: "none" }}>
>     <ReactToPrint
>         ref={r => {
>             prescriptionPadRTPRef.current = r;
>         }}
>         trigger={() => <button>print</button>}
>         content={() =>
>             prescriptionPadRef.current
>         }                                            
>     />
> </div>
> ```
> 
> It would be nice if the print can trigger using state change like:
> 
> ```js
> <ReactToPrint
>     print={true|false}
> />
> ```
> 
> Hopefully to implent it in future. Thank you very much!

Thank

**Comment by vaynevayne** [comment] 2023-09-15 03:06
666, it works

```jsx
 onBeforeGetContent: () => {
      setShowTrash(false)
      return Promise.resolve()
    },
```

**Comment by MatthewHerbst** [comment] 2023-09-15 04:08
> ```js
>  onBeforeGetContent: () => {
>       setShowTrash(false)
>       return Promise.resolve()
>     },
> ```

Do not do this. You risk the Promise resolving before the state update has completed because state updating in React is not synchronous.

**Comment by vaynevayne** [comment] 2023-09-15 06:09
```jsx
 const [counterOptions, setCounterOptions] = useState<any>({ counter: 0, resolve: undefined })
  useEffect(() => {
    const { resolve, ...otherState } = counterOptions
    if (resolve) {
      resolve()
      setCounterOptions({ ...otherState, resolve: undefined })
    }
  }, [counterOptions])

  const onPrint = useReactToPrint({
    content: reactToPrintContent,
    documentTitle: 'AwesomeFileName',

    onBeforeGetContent: () => {
      setShowTrash(false)
      return new Promise((resolve) => {
        setCounterOptions((prevOptions) => ({ counter: prevOptions.counter + 1, resolve }))
      })
    },
    onAfterPrint: () => {
      setShowTrash(true)
    },
    removeAfterPrint: true,
  })
```

Is that the right way to write it?

**Comment by MatthewHerbst** [comment] 2023-09-15 07:29
> Is that the right way to write it?

There is an example of how to do this in the README. https://github.com/gregnb/react-to-print#setting-state-in-onbeforegetcontent
