### ISSUE TITLE
Script Error "Member Not Found" in IE11

### ISSUE THREAD

**Issue by kriyazhao** [MatthewHerbst/react-to-print#75] opened 2018-12-11 20:31 UTC
I am using the latest version of react-to-print, and I couldn't make it to show the print dialog in IE 11 browser. It has the following error in the console `SCRIPT3: Member not found.` Clicking inside for details, it points to the line

```
var p = e.querySelectorAll("canvas");
if ([].concat(toConsumableArray(p)).forEach(function (e, t) {
    e.getContext("2d").drawImage(n[t], 0, 0);
}), !1 !== o) {
    var d = document.querySelectorAll('style, link[rel="stylesheet"]');
    [].concat(toConsumableArray(d)).forEach(function (t, n) {
        var r = e.createElement(t.tagName), o = "";
        if ("STYLE" === t.tagName) {
            if (t.sheet) {
                for (var a = 0; a < t.sheet.cssRules.length; a++)
==>                   o += t.sheet.cssRules[a].cssText + "\r\n";
                r.setAttribute("id", "react-to-print-" + n), r.appendChild(e.createTextNode(o));
            }
        }
        else {
            [].concat(toConsumableArray(t.attributes)).forEach(function (e) {
                r.setAttribute(e.nodeName, e.nodeValue);
            }), r.onload = u.bind(null, "link"), r.onerror = u.bind(null, "link");
        }
        e.head.appendChild(r);
    });
}
```
It works fine in Chrome and Firefox, I am not sure how to proceed now, does anyone have the same issue? Thanks in advance!

**Comment by brittonjg** [comment] 2018-12-11 20:35
A few of us have encountered the Member not found issue, but haven't been able to resolve it https://github.com/gregnb/react-to-print/issues/43

**Comment by cmjuettner** [comment] 2019-02-06 16:12
My corporate application has to support IE11, so I'm hoping this issue can bubble up to a higher priority and it can be fixed soon.  Thanks for the effort.  It works great in non-IE11 environments.  There's a shock.

**Comment by MatthewHerbst** [comment] 2019-02-06 19:30
The cause seems to have been identified in https://github.com/gregnb/react-to-print/issues/43#issuecomment-431198280 but I don't know exactly what the proper functionality on IE should be. Been looking into that, but if anyone has suggestions please let me know.

**Comment by cmjuettner** [comment] 2019-02-08 15:22
Looks like [#43](https://github.com/gregnb/react-to-print/issues/43#issuecomment-431198280) is now transferred to this thread, so I'll add some additional comments here.  

In the IE11 console the logged entry is "SCRIPT5022: Exception thrown and not caught".  The line of code that is called out is found in my application's ../node_modules/react-to-print/lib/index.js. 

IE11 is having a problem with this (line 79):
function _nonIterableSpread() {
    throw new TypeError("Invalid attempt to spread non-iterable instance")
}

From Microsoft:
You included a throw statement in your code, but it was not enclosed within a try block, or there was no associated catch block to trap the error. Exceptions are thrown from within the try block using the throw statement, and caught outside the try block with a catch statement.

To correct this error
•Enclose code that can throw an exception in a try block, and ensure there is a corresponding catch block.
•Make sure your catch statement expects the correct form of exception.
•If the exception is re-thrown, make sure there is another corresponding catch statement.

Maybe your expertise will recognize this issue and it can be fixed.  Thanks

**Comment by MatthewHerbst** [comment] 2019-02-08 19:34
@cmjuettner it's one thing to stop the error from being thrown, that's easy. The harder part is making sure the library still prints the page. Clearly there is functionality that IE isn't happy with, so we need to fix that if we want to keep supporting IE.

**Comment by cmjuettner** [comment] 2019-02-08 19:49
Okay, just to test a workaround I added a try/catch to the a fore mentioned function and that exception goes any but now an new exception is thrown, and the code is real similar to above.
I'm running version 2.0.0-alpha-6.

The following 'if' statement (index.js line 131) is throwing: 
Unable to get property 'forEach' of undefined or null reference

**if (_toConsumableArray(e.querySelectorAll("canvas")).forEach(function(e, t) {**

In Chrome _toConsumableArray(e.querySelectorAll("canvas") returns 'nothing' (i'm guessing null) and Chrome handles that ok.

In IE11, that same call is returning 'undefined' and then it pukes.

Again, for a test workaround I commented out that 'if' statement and IE11 will popup the print modal.

**Comment by jredwayT3** [comment] 2019-02-08 21:53
I would love a fix for IE 11, This is an awesome plugin for React but unfortunately I have to support IE 11.   I am getting the error SCRIPT5022: Exception thrown and not caught in commons.js

**Comment by OmgBrown** [comment] 2019-02-20 21:00
I have a fix for IE 11 on this error: 
In the for lood @ line 138, I added a catch to see if the cssText is a string or not (if not a string it is not recognized by IE11). Here is the condition added before appending to styleCSS:
              
```js
// catch 'member not found' error on cssText

if (typeof node.sheet.cssRules[i].cssText === "string") {
  styleCSS += node.sheet.cssRules[i].cssText + "\r\n";
}
```

**Closed as completed** 2019-02-22 00:27 UTC
Labels: bug, duplicate, IE
